pyhkweb/pyhkweblib/pyhk_blueprint.py
import flask
import logging
import ast
import datetime
import json
import os
import urllib.request, urllib.parse, urllib.error
import requests
import time
import platform
import psutil
import numpy as np

from collections import OrderedDict

from pyhkdremote.data_loader import pyhkd_get_filename, pyhkd_get_latest, pyhkd_get_config_dir, pyhkd_get_names
from pyhkdremote.settings import DATA_LOG_FOLDER
from pyhkdremote.control import pyhkd_set
from livecfg.livecfg import LiveCfg
from .cache import cache
import units.units as units
import gitinfo
from pyhkdlib.instruments.gpib.thales_XPCDE4865 import ThalesXPCDE4865

# Returns the correct function to convert between two units ("K", "C", etc).
# Returns None on failure
def get_unit_func(start, finish):
	funcname = str(start).replace('/','p') + '2' + str(finish).replace('/','p')
	try:
		func = getattr(units, funcname)
		return func
	except AttributeError:
		return None

pyhkpage = flask.Blueprint('pyhkpage', __name__,template_folder='templates')

# Check if a page name is a valid page of the given type.  If so, return 
# it.  If not, return the first such valid page.  If no valid page
# exists, return None.
def find_page_name(cur_page_id, page_config, page_type):

	if cur_page_id is not None:
		if cur_page_id in list(page_config.keys()):
			if page_config[cur_page_id]['page_type'] == page_type:
				return cur_page_id
	
	# We have a bad name, so find the first (in order) valid page name	
	for k in flask.current_app.config['page_ids']:
		if page_config[k]['page_type'] == page_type:
			return k
			
	# No valid pages exist
	return None

# Inject global variables used by all templates
@pyhkpage.context_processor
def inject_settings():
	settings = {
		'page_ids': flask.current_app.config['page_ids'], 
		'maintenance_mode': flask.current_app.config['internal_settings'].get("maintenance_mode", False),
		'site_name': flask.current_app.config['internal_settings'].get("site_name", None),
		'unit_symbol_default': units.unit_symbol_default,
		'unit_id_short': units.unit_id_short
	}
	return settings
    
@pyhkpage.route("/control/pyhkd/", methods=["POST"])
def request_pyhkd_set():
	# pyhkd checks its inputs carefully, no sense repeating that here
	command = flask.request.form.get('command')
	name = flask.request.form.get('name')
	value = flask.request.form.get('value')
	pyhkd_set(command, name, value, retry=False)
	return "Request Sent"

# None for target_date or num_days means to use the current local session value
@pyhkpage.route("/")
@pyhkpage.route("/plot")
@pyhkpage.route("/plot/<cur_page_id>")
@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>")
@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>/")
def plot(cur_page_id=None, target_date=None, num_days=None, plot_mode=0, plot_dt=None):
	
	page_config = flask.current_app.config['page_config']
	cur_page_id = find_page_name(cur_page_id, page_config, page_type='plot')
	
	if cur_page_id is None:
		return "No plot pages exist!", 400
	
	page_title = page_config.get(cur_page_id,{}).get('page_title','Plot')
	plots = page_config[cur_page_id].get("plots", [])
	num_plots = len(plots)
	
	# Build the axis labels
	labels = ['']*num_plots
	unit_labels = ['']*num_plots
	for i in range(num_plots):
		labels[i] = units.unit_id_short.get(plots[i]['subfolder_label'], 'Unknown')
		dflt = units.unit_symbol_default.get(plots[i]['subfolder_label'], '')
		unit_labels[i] = plots[i].get("units", dflt)
		if unit_labels[i]:
			labels[i] += ' [' + unit_labels[i] + ']'
		else:
			unit_labels[i] = 'none' # Value for the url, not shown
		unit_labels[i] = unit_labels[i].replace('/','p')
	
	return flask.render_template("plot.html",   cur_page_id = cur_page_id, 
												page_config = page_config,
												page_title = page_title,
												num_plots = num_plots,
												axis_label = labels,
												target_date = target_date,
												plot_mode = plot_mode,
												plot_dt = plot_dt,
												num_days = num_days,
												unit_labels = unit_labels)

@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>/compare")
@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>/compare/<signed_int:plot_dt>sec")
def plot_compare(cur_page_id, target_date, num_days, plot_dt=None, plot_mode=1):
	return plot(cur_page_id=cur_page_id, target_date=target_date, num_days=num_days, plot_mode=plot_mode, plot_dt=plot_dt)
																				
valid_generic_pages = ["tables", "export", "panel", "thales", "safety_dashboard", "ls224"]
@pyhkpage.route("/<page_type>")
@pyhkpage.route("/<page_type>/<cur_page_id>")
def generic_page(page_type, cur_page_id=None):
	if page_type not in valid_generic_pages:
		return "Invalid page type!", 400
	page_config = flask.current_app.config['page_config']
	cur_page_id = find_page_name(cur_page_id, page_config, page_type=page_type)
	if cur_page_id is None:
		return "No " + page_type + " pages exist!", 400
	page_title = page_config.get(cur_page_id,{}).get('page_title', page_type.capitalize())
	return flask.render_template(page_type + ".html",cur_page_id = cur_page_id, 
												page_config = page_config,
												page_title = page_title,
												axis_labels = units.unit_labels_full)
							
# value_names should be given as repr(list) for passing to ast.literal_eval.
@pyhkpage.route("/data/current/<subfolder_label>/<units_name>/<value_names>.json")
@pyhkpage.route("/data/current/<subfolder_label>/default/<value_names>.json")
def get_data_current(subfolder_label, value_names, units_name='default'):

	# Try to load the unit conversion function
	dflt = units.unit_symbol_default.get(subfolder_label)
	conv_func = None
	#logging.debug("Requested units: " + str(units_name) + " (" + str(subfolder_label) + ")")
	if units_name not in ['default', dflt]:
		conv_func = get_unit_func(dflt, units_name)
		logging.debug("Attempting to load unit conversion from " + str(dflt) + " to " + str(units_name) + ". Found: " + str(conv_func))
	
	# Data comes in as repr(actual_list), so we need to convert it.
	# ast.literal_eval is safe with untrusted strings.
	try:
		value_names = ast.literal_eval(value_names)
	except:
		logging.error("Bad value names passed to get_data_current: " + str(value_names))
		return "", 400
		
	results = OrderedDict()
	for n in value_names:
		ts, v = pyhkd_get_latest(DATA_LOG_FOLDER, subfolder_label, n, return_as_datetime = False)
		if ts is not None:
			
			if v is not None:
				
				if conv_func is not None:
					v = conv_func(v)
				
				# NaN isn't allowed in strict json, was causing some issues.
				# None converts to null and is allowed.
				if not np.isfinite(v):
					v = None
				
			results[n] = (int(1000*ts), v)
			
	return json.dumps(results)
		
	
# Load a day's worth of archived data for a list of sensors, downsampling
# each sensor as needed.  target_date is a string of the form YYYYMMDD.
# value_names should be given as repr(list) for passing to ast.literal_eval.
# max_points_each is max reported points for all days for one value_name.
# Currently each day for each value_name will be downsampled to
# max_points_each/num_days points, but this may change in the future.
PLOTMODE_NORMAL = 0
PLOTMODE_LIVECOMPARE = 1
PLOTMODE_FASTDATA = 2
VALID_PLOTMODES = [PLOTMODE_NORMAL, PLOTMODE_LIVECOMPARE, PLOTMODE_FASTDATA]

MAX_TOTAL_POINTS = 30000
PLOT_URL = "/data/archive/<target_date>/mode<int:plot_mode>/<signed_int:plot_dt>sec/<int:num_days>/<subfolder_label>/<units_name>/<value_names>.csv"
@pyhkpage.route(PLOT_URL)
@pyhkpage.route(PLOT_URL.replace("<target_date>", "today"))
def get_data_archive(subfolder_label, value_names, units_name='default', target_date = None, num_days = 1, plot_mode = PLOTMODE_NORMAL, 
	plot_dt = 0, max_points_each = 5000):
	
	logging.debug("Data archive requested")
	
	if target_date is None:
		target_date = datetime.date.today()
	else:
		try:
			target_date = datetime.datetime.strptime(target_date, '%Y%m%d').date()
		except ValueError:
			logging.error("Bad target date passed to get_data_archive: " + str(target_date))
			return "", 400

	if plot_mode not in VALID_PLOTMODES:
		plot_mode = PLOTMODE_NORMAL
		
	try:
		num_days = int(num_days)
	except:
		logging.error("Bad day count passed to get_data_archive: " + str(num_days))
		return "", 400
	
	# Restrict the date range
	num_days = np.clip(num_days, 1, 14)

	# Data comes in as repr(actual_list), so we need to convert it.
	# ast.literal_eval is safe with untrusted strings.
	try:
		value_names = ast.literal_eval(value_names) 
		if not isinstance(value_names, list):
			value_names = [value_names]
	except:
		logging.error("Bad value names passed to get_data_archive: " + str(value_names))
		return "", 400
		
	# Set harsher point count limits for very busy plots
	max_points_each = min(max_points_each, int(MAX_TOTAL_POINTS / len(value_names)))
	
	# Set harsher point count limits for very busy plots
	max_points_each = min(max_points_each, int(MAX_TOTAL_POINTS / len(value_names)))
	
	# We can't use the cached function for today or the future, both
	# to prevent incomplete data loads and to keep it from caching
	# for a day that isn't complete. 
	if target_date < datetime.date.today() and plot_mode == PLOTMODE_NORMAL:
		return get_data_archive_helper(subfolder_label, value_names, 
					target_date, num_days, max_points_each, units_name, 
					plot_mode=0, plot_dt=0)
	else:
		logging.debug("Skipping data archive cache, date isn't in the past")
		return get_data_archive_helper.uncached(subfolder_label, value_names, 
					target_date, num_days, max_points_each, units_name, 
					plot_mode, plot_dt)


# Cached helper function doing the data loading/processing for
# get_data_archive.  Assumed inputs are already verified and transformed 
# to their proper types - value_names is a list, target_date is a 
# datetime.date, num_days is a postive integer.
@cache.memoize()
def get_data_archive_helper(subfolder_label, value_names, target_date, 
	num_days, max_points_each, units_name, plot_mode, plot_dt):
		

pyhkweb/templates/about.html
{% extends "base-page.html" %}

{% block header %}
{% endblock %}

{% block content %}

</p>	

<h3>Server Information</h3>
<p>
<b>Hostname:</b> {{server_hostname}} <br>
<b>Platform:</b> {{server_platform}} <br>
<b>CPU Count:</b> {{server_ncpu}} <br>
<b>Python Version:</b> {{server_pyver}} <br>
<br>
<b>CPU Load (1,5,15 min):</b> {{server_load1}}, {{server_load5}}, {{server_load15}} <br>
<b>RAM Usage:</b> {{server_ramused|round(1)}} / {{server_ramtot|round(1)}} GB<br>
<br><i>Note that the CPU load and RAM usage shown above includes all running processes.</i>
</p>	

{% endblock %}

pyhkweb/templates/base-page.html
<!doctype html>
<html>

<head>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	
	{% block header %}{% endblock %}
	
	<title>{{site_name|e if site_name else "PyHK"}} - {{page_title}}</title>
	
	<style>
		body {
			margin: 0;
			font-family: Arial, Helvetica, sans-serif;
		}
		
		.mainnavpanel ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			width: 200px;
			background-color: #616265;
			position: fixed;
			z-index: 100000;
			height: 100%;
			overflow: auto;
			
		}

		.mainnavpanel li a, .mainnavpanel li h3, .mainnavpanel li h4 {
			display: block;
			color: #000;
			padding: 7px 16px;
			text-decoration: none;
			color: white;
		}


		.mainnavpanel li a.active {
			background-color: #FF6E1E;
			color: white;
		}

		.mainnavpanel li a:hover:not(.active) {
			background-color: #76777B;
			color: white;
		}
		
		/* Highlight every other */
		.prettytable:not(.prettytable-quad) tr:nth-child(odd) {
			background-color: #E0E0E0
		}
		
		/* Highlight groups of four */
		.prettytable-quad tr:nth-child(8n+6) {
		  background: #E0E0E0;
		}
		.prettytable-quad tr:nth-child(8n+7) {
		  background: #E0E0E0;
		}
		.prettytable-quad tr:nth-child(8n+8) {
		  background: #E0E0E0;
		}
		.prettytable-quad tr:nth-child(8n+9) {
		  background: #E0E0E0;
		}
				
		.prettytable td {
			padding: 6px;
			text-align: center;
		}
		.prettytable th {
			padding: 6px;
			text-align: center;
			font-weight: bold;
			background-color: #FF6E1E;
			color: white;
		}
		.prettytable {
			font-size: 14px;
		}
		table {
			border-collapse: collapse;
			border-color: black;
		}
		.column {
			float: left;
			padding: 10px;
		}
		.clearfix::after {
			content: "";
			clear: both;
			display: table;
		}		
		
		@keyframes updatepinganim 
		{
			0% 
			{
				text-shadow: 0 0 1px black;
			}
			100% 
			{
				text-shadow: none;
			}
		}
		
		.newvalue 
		{
			animation-duration: 2s;
			animation-timing-function: ease-in;
			animation-delay: 0s;
			animation-iteration-count: 1;
			animation-name: updatepinganim;
		}
		
		/* jquery UI theme */
		
		.ui-datepicker {
			font-size: 11px;
		}
		
		.ui-state-active,
		.ui-widget-content .ui-state-active,
		.ui-widget-header .ui-state-active,
		a.ui-button:active,
		.ui-button:active,
		.ui-button.ui-state-active:hover {
			border: 1px solid #616265;
			background: #FF6E1E;
			font-weight: normal;
			color: #ffffff;
		}
		.ui-state-highlight,
		.ui-widget-content .ui-state-highlight,
		.ui-widget-header .ui-state-highlight {
			border: 1px solid #FF6E1E;
			background: #f6f6f6;
			color: #454545;
		}
		
		.ui-corner-all,
		.ui-corner-top,
		.ui-corner-left,
		.ui-corner-tl {
			border-top-left-radius: 0;
		}
		.ui-corner-all,
		.ui-corner-top,
		.ui-corner-right,
		.ui-corner-tr {
			border-top-right-radius: 0;
		}
		.ui-corner-all,
		.ui-corner-bottom,
		.ui-corner-left,
		.ui-corner-bl {
			border-bottom-left-radius: 0;
		}
		.ui-corner-all,
		.ui-corner-bottom,
		.ui-corner-right,
		.ui-corner-br {
			border-bottom-right-radius: 0;
		}
		
		/* Hide the arrows for number fields */
		input[type='number'] {
			-moz-appearance:textfield;
		}
		input[type=number]::-webkit-inner-spin-button,
		input[type=number]::-webkit-outer-spin-button {
			-webkit-appearance: none;
			margin: 0;
		}
	</style>
	
	<script type="text/javascript">
		
		$( document ).ready(function() 
		{
			const url_params = new URLSearchParams(window.location.search);
			
			// Hide the main navigation panel and page title
			if (url_params.get('hidenav') == 'true')
			{
				document.getElementById("mainnavpanel").style["display"] = "none";
				document.getElementById("pagetitleheading").style["display"] = "none";
				document.getElementById("mainpagecontents").style["margin-left"] = "0px";
				document.getElementById("mainpagecontents").style["padding"] = "0px";
				
			}
		});
		
	</script>
	
</head>

<body>
	% if maintenance_mode
		<div style="background-color: yellow; border: 2px solid red; padding: 2px; font-weight: bold; text-align: center;">
		The website is currently in maintenance mode.  You may continue to use it, but you may notice disruptions as code is updated.
		</div>
	% endif

	<div class="mainnavpanel" id="mainnavpanel">
	
		<ul>
			<li style="text-align: center; margin: 18px 4px">
				% if site_name
					<h3 style="font-size: 24px; font-weight:bold; padding: 0px 0px; margin: 4px 16px">{{site_name|e}}</h3>
					<h4 style="font-size: 14px; font-weight:normal; padding: 0px 0px; margin: 4px 16px">Data Acquisition System</h4>
				% else
					<h3 style="font-size: 18px; font-weight:bold; padding: 0px 0px; margin: 4px 16px">Data Acquisition System</h3>
				% endif
			</li>
			% for dn in page_ids
				% set active_str = ""
				% if dn == cur_page_id
					% set active_str = "active "
				% endif
				
				% with pt = page_config[dn]["page_type"]
				
					<li><a class="{{active_str}}pagelink_{{pt}}" id="pagelink_{{dn}}" href=			

					% if pt in ["plot", "ls370", "hkmb"]
						"{{ url_for('pyhkpage.' + pt, cur_page_id=dn) }}"
					% elif pt in ["fridge", "camera", "about"]
						"{{ url_for('pyhkpage.' + pt) }}"
					% elif pt not in ["internal_settings"]
						"{{ url_for('pyhkpage.generic_page', page_type=pt, cur_page_id=dn) }}"
					% endif
				% endwith
				
				>{{page_config[dn]["page_title"]}}</a></li>
				
			% endfor
		</ul>
		
	</div>

	<div style="margin-left:210px;padding:1px 16px;" id="mainpagecontents">
		<h2 id="pagetitleheading">{{page_title}}{% block titlesuffix %}{% endblock %}</h2>
		{% block content %}{% endblock %}
	</div>
	
</body>
	
</html>

pyhkweb/templates/livedata-base-page.html
{% extends "base-page.html" %}
		
{% block header %}
		
	<script type="text/javascript">
		
		var si_prefix = {
			'-24': 'y',
			'-21': 'z',
			'-18': 'a',
			'-15': 'f',
			'-12': 'p',
			'-9': 'n',
			'-6': 'μ',
			'-3': 'm',
			'0': '',
			'3': 'k',
			'6': 'M',
			'9': 'G',
			'12': 'T',
			'15': 'P',
			'18': 'E',
			'21': 'Z',
			'24': 'Y'
		};
		
		var unit_symbol_default = {{ unit_symbol_default|tojson }};
		unit_symbol_default['resistance'] = 'Ω'; // Override for web
		var unit_id_short = {{ unit_symbol_default|tojson }};
				
		// Min and max prefix powers to use for different units.
		// Child pages can overwrite these.  Useful if, for example,
		// you want to restrict temperatures to only show either K or mK
		// but never kK.
		var unit_lims = {
			'temperature': [-3,0],
			'angle': [0,0],
			'percentage': [0,0],
			'fraction': [0,0],
			'relhumidity': [0,0],
			'pressure': [-24,0],
		};
		
		// Units for which a space should not be included between the
		// number and the unit label
		var unit_spaceless = ['percentage'];
				
		// Generate a lookup table of functions to handle each of the
		// incomming data types
		var new_data_func = {};
		for (subfolder_label in unit_symbol_default)
		{
			let lbl = subfolder_label; // Freeze in the value for this scope
			new_data_func[lbl] = function(d){return new_data_generic(d, lbl)};
		}
		
		// Process incomming data
		function new_data_generic(data, subfolder_label)
		{
			var tar_prefix = 'val_' + subfolder_label + '_';
			
			units = unit_symbol_default[subfolder_label];
			
			console.log("New data received (" + subfolder_label + ")");
			
			for (tname in data)
			{
				if (data[tname][1] == null || data[tname][1] === '')
				{
					val = "None";
				}
				else if (units == null || units === '')
				{
					// No units or prefixes, use default string representation
					// which should handle integers and floating points
					// fairly gracefully
					val = data[tname][1];
				}
				else
				{
					val = data[tname][1];
										
					var lims = unit_lims[subfolder_label];
					if (lims == undefined)
						lims = [-12, 12];
										
					sign = '';
					if (val < 0)
						sign = '-';
					val = Math.abs(val);
					
					// Find the closest SI prefix
					power = Math.round((Math.log10(val)-1.0) / 3) * 3;
					if (power < lims[0])
						power = lims[0];
					else if (power > lims[1])
						power = lims[1];	
					if (power in si_prefix)
					{
						prefix = si_prefix[power];
					}
					else
					{
						power = 0;
						prefix = '';
					}
					
					val *= Math.pow(10, -power);
					
					// Try to show 4 sig figs
					if (val >= 99.995)
						// 99.995 is the first number to round to 
						// 100.00 if it was shown with two 
						// decimal places, so show it as 100.0						
						val = val.toFixed(1);
					else if (val >= 9.9995)
						val = val.toFixed(2);
					else
						// Don't show extreme numbers of decimal places,
						// we already have the SI prefixes so the number
						// is very small
						val = val.toFixed(3);
						
					// Most of the time we want a space after the number
					if (!unit_spaceless.includes(subfolder_label) && (units.length > 0))
					{
						prefix = '&nbsp;' + prefix;
					}
					
					val = sign + val + prefix + units;
				}
				
				$("[id='" + tar_prefix + escape(tname) + "']").html(val);
			}
			
		}
			
		function request_set(input_id, target_name, command, scale)
		{	
			var val = $("[id='" + escape(input_id) + "']").val();
			if (scale != null)
				val = parseFloat(val) / scale;
			request_set_val(target_name, command, val);
		}
		
		function request_set_val(target_name, command, val)
		{	
			console.log("Requesting " + command + ", " + target_name + ", " + val);
			$.post("{{ url_for('pyhkpage.request_pyhkd_set') }}", {"command": command, "name": target_name, "value": val}, function(result) {console.log("Server Result: " + result);});
		}
				
		function request_set_t(input_id, target_name) {request_set(input_id, target_name, 'tset', 1);}
		function request_set_v(input_id, target_name) {request_set(input_id, target_name, 'vset', 1);}
		function request_set_p(input_id, target_name) {request_set(input_id, target_name, 'pset', 1000);}
		function request_set_t(input_id, target_name) {request_set(input_id, target_name, 'tset', 1);}
		function request_set_i(input_id, target_name) {request_set(input_id, target_name, 'iset', 1);}
		function request_set_ir(input_id, target_name) {request_set(input_id, target_name, 'irset', 1);}
		function request_set_s(input_id, target_name) {request_set(input_id, target_name, 'sset', null);}
		function request_set_per(input_id, target_name) {request_set(input_id, target_name, 'perset', 1);}
		
		function request_set_val_s(target_name, val) {request_set_val(target_name, 'sset', val);}
		
		function request_set_v_zero(input_id, target_name) 
		{
			$("[id='" + escape(input_id) + "']").val(0);
			request_set_v(input_id, target_name);
		}
                                    
				
	</script>
{% endblock %}

pyhkweb/templates/ls224.html
{% extends "base-page.html" %}

{% block header %}
{% endblock %}

{% block content %}

</p>	

<p>
<b>Sensor Type:</b> Diode <br>
<b>Range:</b> 2.5 V (Silicon) <br>
<b>Curve:</b> 02 DT-670 <br>
</p>	

{% endblock %}

pyhkweb/templates/panel.html
{% extends "livedata-base-page.html" %}

{# Assemble the list of sensors we need updates from for each type. #}
{# This is kind of awkward to do in Jinja2, maybe there is a cleaner way? #}
% set update_list = {}	
% for w in page_config[cur_page_id]['widgets']	
	% if w['widget_type'] == 'heater_control'
		% for sl in ['power', 'voltage']	
			% set tmp = update_list.get(sl, []) + [w['name_v']]
			% set tmp = update_list.update({sl: tmp})
		% endfor
		% set tmp = update_list.get('temperature', []) + [w['name_t']]
		% set tmp = update_list.update({'temperature': tmp})
	% elif w['widget_type'] == 'value'
		% if ('subfolder_label' in w) and ('name' in w)
			% set tmp = update_list.get(w['subfolder_label'], []) + [w['name']]
			% set tmp = update_list.update({w['subfolder_label']: tmp})
		% endif
	% endif	
% endfor

{% block header %}

	<style>

		.widget {
			width: {{page_config[cur_page_id]['widget_width']}}px;
			height: {{page_config[cur_page_id]['widget_height']}}px;
			line-height: {{page_config[cur_page_id]['widget_height']}}px;
			/* border: 1px solid black; */ /* debugging */
			text-align: center;
		}
		
		.widget-inner {
			font-size: 16px;
			line-height: 24px;
			position: relative;
			top: 50%;
			 -webkit-transform: translateY(-50%);
			-ms-transform: translateY(-50%);
			transform: translateY(-50%);
		}
		
		.tight-number {
			-webkit-appearance:     none;
			-moz-appearance:        none;
			-ms-appearance:         none;
			-o-appearance:          none;
			appearance:             none;
			padding-left: 3px;
			padding-right: 3px;
			margin-left: -3px;
			margin-right: -3px;
		}
		.tight-button {
			font-family: Arial, Helvetica, sans-serif;
			font-size: 12px;
			-webkit-appearance:     none;
			-moz-appearance:        none;
			-ms-appearance:         none;
			-o-appearance:          none;
			appearance:             none;
			padding-left: 2px;
			padding-right: 2px;
			margin-left: -2px;
			margin-right: -2px;
		}
		
	</style>
	
	{{ super() }}
	
	<script type="text/javascript">
		
		unit_lims['voltage'] = [-3,0];
		unit_lims['power'] = [-6,0];
	
		function update_data() 
		{
			console.log("Requesting new data");
			
			{# Use the auto-generated list of sensors assembled at the top #}
			% for sublbl in update_list
				
				// {{ sublbl }}: {{ update_list[sublbl]|tojson }}
				$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label=sublbl, value_names=update_list[sublbl]) }}", new_data_func["{{ sublbl }}"]);
				
			% endfor
		}	
		
		$( document ).ready(function() 
		{
			update_data();
			var update_timer = setInterval(update_data, 500); // Panels are low data volumes so we can update a little faster
		});
		
	</script>
		
{% endblock %}

{% block content %}
	
	<div style="position: relative;">
		
		<img src="{{url_for('static', filename=page_config[cur_page_id]['background'])}}">
	
		% for w in page_config[cur_page_id]['widgets']
		
		<div class="widget" style="position: absolute; left: {{w['xpos']}}px; top: {{w['ypos']}}px;">
			<div class="widget-inner">
				
				% if w['widget_type'] == 'heater_control'
			
					<b>{{w['label']}}</b><br>
					<span id="val_temperature_{{ w['name_t']|urlencode }}">-</span><br>
					<span id="val_voltage_{{ w['name_v']|urlencode }}">-</span>&nbsp;/&nbsp;<span id="val_power_{{ w['name_v']|urlencode }}">-</span><br>
					
					<input class="tight-number" type="number"  id="toset_{{ w['name_v']|urlencode }}" style="width:45px; margin-right:5px; margin-top:8px;"></input>
					<span>
						<button class="tight-button" onclick="request_set_v('toset_{{ w['name_v']|e }}', '{{ w['name_v']|e }}')"> V </button>
						<button class="tight-button" onclick="request_set_p('toset_{{ w['name_v']|e }}', '{{ w['name_v']|e }}')"> mW </button>
						<button class="tight-button" onclick="request_set_v_zero('toset_{{ w['name_v']|e }}', '{{ w['name_v']|e }}')"> 0 </button>
					</span>
					
				% elif w['widget_type'] == 'value'
				
					<span id="val_{{ w['subfolder_label'] }}_{{ w['name']|urlencode }}">-</span><br>
				
				% endif
			
			</div>
		</div>
		
		% endfor
		
	</div>	

{% endblock %}

pyhkweb/templates/simple-code.html
<!doctype html>
<html>

<head>
	
	<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
	
	<title>{{cur_page_name}}</title>
	
	<style>
		pre
		{
			-moz-tab-size: 4;
			-o-tab-size:   4;
			tab-size:      4;
		}
	</style>
	
</head>

<body>
	
	<pre class="prettyprint">{{code_text}}</pre>
	
</body>
	
</html>